### ISSUE TITLE
Aliases in Exercise folders

### ISSUE THREAD

**Issue by andreasthoelke** [damncabbage/ylj16-workshop#7]
The workshop looks super helpful/comprehensive, thank you!

I noticed that the `bower.json` files in the exercise folders are aliases not real files. (e.g. at https://github.com/damncabbage/purescript-workshop/tree/master/01%20Basics/01%20Building%20Things%2C%20Finding%20Things%2C%20Trying%20Things/Exercise )

Could you perhaps commit the bower.json and package.json files?

**Comment by andreasthoelke** [comment]
Sorry, just noticed the files are in the repo under `/common`. I just had to delete the `bower_components` alias in the Exercise folder to get `bower install` and `npm install` working.

**Comment by damncabbage** [comment]
Thanks! And sorry, the bower+npm bit of this is a bit hacky / convoluted.
