### ISSUE TITLE
Indicate the required versions of PureScript, Node, NPM

### ISSUE THREAD

**Issue by FranklinChen** [damncabbage/ylj16-workshop#8]
I know this repo is a year old now and things move fast, but it might be helpful to indicate the required versions of PureScript, Node, and NPM for the materials here to work. For example, I ran the bootstrap script and it appears to want Node < 7 and NPM == 3. I don't know what version of PureScript is appropriate.

**Comment by damncabbage** [comment]
Good idea; thanks. I was thinking of giving this a workover now that the [new Pux release just landed](https://github.com/alexmingoia/purescript-pux/releases/tag/v8.0.0).

In the very short term to get you the info: this uses PureScript 0.9.3, Node 6.x and NPM 3.x. The latter can be bumped with no problem, but bumping the former (PureScript) needs a bunch of library upgrades.

The `package.json` under `common/` lists the PureScript version; it's what gets installed when the `npm install` is kicked off. The version is encoded, but isn't listed in the README, no.

**Comment by damncabbage** [comment]
(How did you find this repo, by the way?)

**Comment by damncabbage** [comment]
Fixed by c190f36; thanks for putting in the issue. :)

**Comment by FranklinChen** [comment]
I don't remember any more how I found this repo. I saw a link to it somewhere online just today.
